version: '3'
services:

  kibana:
    image: kibana:7.9.3
    # environment:
    #     - ELASTICSEARCH_URL=http://elasticsearch-dev:9200
    #     - elasticsearch.hosts=http://elasticsearch-dev:9200
    ports:
        - "5601:5601"
    links: ['elasticsearch']
    depends_on: ['elasticsearch']
    networks: ['elastic-stack']  

  elasticsearch:
    # image: elasticsearch:7.9.3
    build:
        context: ./
        dockerfile: ./Dockerfile
    environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        - xpack.monitoring.enabled=true
    ports:
        - "9200:9200"
        - "9300:9300"
    networks: ['elastic-stack']

networks:
    elastic-stack: {}
          